### ISSUE TITLE
Clicking one 'refresh' button causes all buttons to animate

### ISSUE THREAD

**Issue by damienmckenna** [mglaman/drupalorg-issue-tracker#18]
When you click the "refresh" button for one issue it triggers all of the 'refresh' buttons to animate; if all of the issues are refreshed then the refresh button should be outside of the table, possibly in the header bar, otherwise the bug should be fixed.

**Comment by mglaman** [comment]
Yeah, this is a bug. I didn't know about directives and the global check to see if ajax was in progress affected them all.
