### ISSUE TITLE
Removed issues keep coming back

### ISSUE THREAD

**Issue by benjy** [mglaman/drupalorg-issue-tracker#25]
I keep clicking the "x" to remove issues that are "Fixed" from the list and then they come back again.

**Comment by mglaman** [comment]
I haven't been able to reproduce yet. I think the issue might be chrome.storage.local failing to write (?) and need to add more error detection into the app.

**Comment by benjy** [comment]
Not sure, if you have some debugging code I have the repo checked out, happy to drop it in.

**Comment by benjy** [comment]
I think this is related to the "auto refresh". It seems to be that which brings them back.

**Comment by mglaman** [comment]
That actually makes a lot of sense. Issues are refreshed as their own controller. When deleted the controller needs to be destroyed.

I'm hitting finals week for my class so I may or may not be able to fiddle with this soon.
