### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by benjy14** [mglaman/drupalorg-issue-tracker#9]
When I open the app, this is what I see: ![screen shot 2015-01-03 at 7 49 01 am](https://cloud.githubusercontent.com/assets/863137/5600761/0ea23628-931d-11e4-8896-4aef7dd442b4.png) The operation links seem a little funny?

When I try to enter an issue number and click "Add", it opens in my main Chrome window with this URL: chrome-extension://invalid/

I installed this from the Chrome web store, I can try again by cloning the codebase?

Chrome version: Version 39.0.2171.95 (64-bit)

Not sure if i've missed some configuration or whether it is just broken. If I can give you more debug info, let me know.

**Comment by mglaman** [comment]
Well :( That's no good. It sounds like maybe it is just broken through Chrome Web Store - I'll have to do some digging.

But yeah, if you clone down dev branch, follow instructions in README.md to load the unpacked version.

I'll try to get store thing figured out as soon as possible.

**Comment by mglaman** [comment]
@benjy14 I've just pushed v1.0.4 and added it to the Web Store. It adds Bootstrap's alerts to hopefully add some idea of errors. However this is depicting an error causing AngularJS to break.

**Comment by mglaman** [comment]
@benjy14 The build task is screwed up, first time using Bower/Grunt and I probably did something stupid. Vendor resources weren't being bundled.

I just pushed v1.0.5 to the store, this should fix. Let me know https://chrome.google.com/webstore/detail/drupal-issue-tracking/gigmieclehjecoglmlmgokcekfklonmb!

**Comment by benjy14** [comment]
@mglaman Still seems to be 1.0.4 for me on the Webstore, maybe it takes a while to update?

**Comment by benjy14** [comment]
Ok, it is working now but the icons are still broken.

**Comment by mglaman** [comment]
Thanks @benjy14! The font resources are copying during the build. I'll work on revising the build process over the weekend and get this fixed up

**Comment by mglaman** [comment]
Build task and font issue has been fixed.
